# Generated by Django 2.1.5 on 2019-05-09 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estruturacurricular',
            name='ano_periodo',
            field=models.CharField(default='2019.1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estruturacurricular',
            name='sigla',
            field=models.CharField(default='02', max_length=10),
            preserve_default=False,
        ),
    ]
