# Generated by Django 2.1.5 on 2019-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190509_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.CharField(choices=[('1', 'Primeiro Horário'), ('2', 'Segundo Horário'), ('3', 'Terceiro Horário'), ('4', 'Quarto Horário'), ('5', 'Quinto Horário'), ('6', 'Sexto Horário')], max_length=1)),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('ordem', 'turno')},
        ),
    ]
