# Generated by Django 2.2.1 on 2019-08-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190805_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
