# Generated by Django 2.1.5 on 2019-08-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('site', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla', models.CharField(max_length=10)),
                ('capacidade', models.IntegerField()),
                ('tamanho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bloco', models.CharField(max_length=10)),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Centro')),
            ],
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
