# Generated by Django 2.1.5 on 2019-08-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190815_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('turno', models.CharField(max_length=3)),
                ('habilitacao', models.CharField(max_length=250)),
                ('modalidade', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('site', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='hora_fim',
            new_name='hora_final',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='estrutura',
            new_name='centro',
        ),
        migrations.RemoveField(
            model_name='centro',
            name='codigo',
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda'), ('3', 'Terça'), ('4', 'Quarta'), ('5', 'Quinta'), ('6', 'Sexta'), ('7', 'Sábado')], default='2', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Departamento'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('dia', 'turno', 'ordem')},
        ),
        migrations.AddField(
            model_name='departamento',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Centro'),
        ),
        migrations.AddField(
            model_name='curso',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Centro'),
        ),
    ]
