# Generated by Django 2.1.5 on 2019-08-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190825_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentecurricular',
            old_name='carga_horaria',
            new_name='ch_pratica',
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='ch_teorica',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='ch_total',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
