# Generated by Django 2.1.5 on 2019-08-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_componentecurricular_requisitos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentecurricular',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='corequisito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_requisitos', to='core.ComponenteCurricular'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='equivalencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equivalencias', to='core.ComponenteCurricular'),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='requisito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_requisitos', to='core.ComponenteCurricular'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='ementa',
            field=models.TextField(max_length=500),
        ),
    ]
