# Generated by Django 2.1.5 on 2019-08-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190826_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecurricular',
            name='corequisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_requisitos', to='core.ComponenteCurricular'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='equivalencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equivalencias', to='core.ComponenteCurricular'),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_requisitos', to='core.ComponenteCurricular'),
        ),
    ]
