# Generated by Django 2.1.5 on 2019-09-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190826_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='habilitacao',
            new_name='nivel',
        ),
        migrations.AddField(
            model_name='centro',
            name='id_unidade',
            field=models.IntegerField(default=1482, unique=True),
            preserve_default=False,
        ),
    ]
