# Generated by Django 2.1.5 on 2019-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190908_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='grau',
            field=models.CharField(default='BACHARELADO', max_length=250),
            preserve_default=False,
        ),
    ]
