# Generated by Django 2.1.5 on 2019-09-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_curso_grau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.CharField(max_length=15),
        ),
    ]
