# Generated by Django 2.1.5 on 2019-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190908_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='codigo',
            field=models.IntegerField(default=1482, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.IntegerField(default=1800, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_unidade',
            field=models.IntegerField(default=1800, unique=True),
            preserve_default=False,
        ),
    ]
