# Generated by Django 2.1.5 on 2019-09-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190910_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='sigla',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='sigla',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
