# Generated by Django 2.1.7 on 2019-09-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190910_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecurricular',
            name='ch_docente',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='ch_ead',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='ch_estagio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='cr_max_ead',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='id_componente',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='modalidade',
            field=models.CharField(default='Presencial', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='nivel',
            field=models.CharField(default='G', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='tipo',
            field=models.CharField(default='Disciplina', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='corequisito',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='equivalencia',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='componentecurricular',
            name='requisito',
            field=models.TextField(max_length=500),
        ),
    ]
