# Generated by Django 2.1.7 on 2019-10-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191003_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ano_entrada_vigor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_atividade_obrigatoria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_complementar_minima',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_ideal_semestre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_maxima_semestre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_minima_semestre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_nao_atividade_obrigatoria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_optativas_minima',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_total_minima',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_ideal_semestre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_maximo_semestre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_minimo_semestre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_nao_atividade_obrigatorio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_total_minimo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='max_eletivos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='meses_conclusao_ideal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='meses_conclusao_maximo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='meses_conclusao_minimo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='observacao',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='periodo_entrada_vigor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='semestre_conclusao_ideal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='semestre_conclusao_maximo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='semestre_conclusao_minimo',
            field=models.IntegerField(null=True),
        ),
    ]
