# Generated by Django 2.1.7 on 2019-10-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191003_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruturacurricular',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
