# Generated by Django 2.1.7 on 2019-10-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191003_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizacaocurricular',
            old_name='periodo',
            new_name='semestre',
        ),
        migrations.RemoveField(
            model_name='organizacaocurricular',
            name='obrigatoria',
        ),
        migrations.AddField(
            model_name='organizacaocurricular',
            name='id_curriculo_componente',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacaocurricular',
            name='nivel',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacaocurricular',
            name='tipo_vinculo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
