# Generated by Django 2.2.7 on 2019-11-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191103_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=10)),
                ('formacao', models.CharField(max_length=50)),
                ('tipo_jornada_trabalho', models.CharField(max_length=50)),
                ('vinculo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('classe_funcional', models.CharField(max_length=50)),
                ('id_unidade_lotacao', models.IntegerField()),
                ('lotacao', models.CharField(max_length=150)),
                ('admissao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.IntegerField(unique=True)),
                ('codigo_turma', models.CharField(max_length=50)),
                ('siape', models.IntegerField()),
                ('matricula_docente_externo', models.IntegerField()),
                ('observacao', models.CharField(max_length=50)),
                ('id_componente', models.IntegerField()),
                ('ch_dedicada_periodo', models.IntegerField()),
                ('nivel_ensino', models.CharField(max_length=50)),
                ('campus_turma', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao_horário', models.CharField(max_length=50)),
                ('total_solicitacoes', models.IntegerField()),
                ('capacidade_aluno', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('distancia', models.BooleanField()),
                ('data_consolidacao', models.DateField()),
                ('agrupadora', models.BooleanField()),
                ('id_turma_agrupadora', models.IntegerField()),
                ('qtd_aulas_lancadas', models.IntegerField()),
                ('situacao_turma', models.CharField(max_length=50)),
                ('convenio', models.CharField(max_length=50)),
                ('modalidade_participantes', models.CharField(max_length=50)),
            ],
        ),
    ]
