# Generated by Django 2.2.7 on 2019-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191124_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
