# Generated by Django 2.2.7 on 2019-11-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191124_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='matricula_docente_externo',
            field=models.IntegerField(null=True),
        ),
    ]
