# Generated by Django 2.2.7 on 2019-11-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20191125_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='id_turma_agrupadora',
            field=models.IntegerField(null=True),
        ),
    ]
