# Generated by Django 2.2.7 on 2019-11-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20191125_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='id_componente',
        ),
        migrations.AddField(
            model_name='turma',
            name='componente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.ComponenteCurricular'),
            preserve_default=False,
        ),
    ]
