# Generated by Django 2.2.7 on 2019-11-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20191125_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='qtd_aulas_lancadas',
            field=models.IntegerField(null=True),
        ),
    ]
