# Generated by Django 2.2.7 on 2019-11-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20191125_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='total_solicitacoes',
            field=models.IntegerField(null=True),
        ),
    ]
