# Generated by Django 2.2.7 on 2019-11-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191125_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='id_turma',
            field=models.IntegerField(),
        ),
    ]
