# Generated by Django 2.2.7 on 2019-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191125_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='siape',
            field=models.IntegerField(null=True),
        ),
    ]
