# Generated by Django 2.2.7 on 2019-11-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20191125_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='observacao',
            field=models.CharField(max_length=250),
        ),
    ]
