# Generated by Django 3.0.2 on 2020-03-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20191125_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_turma', models.CharField(max_length=50)),
                ('siape', models.IntegerField(null=True)),
                ('matricula_docente_externo', models.IntegerField(null=True)),
                ('campus_turma', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('descricao_horario', models.CharField(max_length=150)),
                ('capacidade_aluno', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ComponenteCurricular')),
            ],
        ),
    ]
