# Generated by Django 3.0.2 on 2020-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_sugestaoturma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecurricular',
            name='codigo',
            field=models.CharField(max_length=25),
        ),
    ]
