# Generated by Django 3.0.2 on 2020-03-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200324_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugestaoturma',
            name='siape',
        ),
        migrations.AddField(
            model_name='sala',
            name='campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sugestaoturma',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Docente'),
        ),
        migrations.AlterField(
            model_name='sugestaoturma',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Sala'),
        ),
        migrations.AlterField(
            model_name='sugestaoturma',
            name='matricula_docente_externo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sugestaoturma',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='agrupadora',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='convenio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Docente'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_turma_agrupadora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='matricula_docente_externo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='observacao',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
