# Generated by Django 3.0.2 on 2020-03-24 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200324_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='agrupadora',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='docente',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Docente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='id_turma_agrupadora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='observacao',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
