# Generated by Django 3.0.2 on 2020-03-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200324_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='matricula_docente_externo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
