# Generated by Django 3.0.2 on 2020-03-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200324_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='convenio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
