# Generated by Django 3.0.2 on 2020-03-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200325_2218'),
        ('core', '0045_auto_20200324_1947'),
    ]

    operations = [
    ]
