# Generated by Django 3.0.4 on 2020-04-02 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_merge_20200325_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Docente'),
        ),
    ]
