# Generated by Django 3.0.4 on 2020-04-11 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200402_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoGratificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('situacao_servidor', models.CharField(max_length=25)),
                ('id_unidade', models.IntegerField()),
                ('lotacao', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=15)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(null=True)),
                ('id_unidade_designacao', models.IntegerField()),
                ('unidade_designacao', models.CharField(max_length=200)),
                ('atividade', models.CharField(max_length=100)),
                ('observacoes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurmaEstendida',
            fields=[
                ('turma_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Turma')),
            ],
            bases=('core.turma',),
        ),
    ]
