# Generated by Django 3.0.4 on 2020-04-14 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_sugestaoturma_criada_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugestaoturma',
            old_name='criada_por',
            new_name='criador',
        ),
    ]
