# Generated by Django 3.0.4 on 2020-04-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200413_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoTurmaEstendida',
            fields=[
                ('sugestaoturma_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SugestaoTurma')),
            ],
            bases=('core.sugestaoturma',),
        ),
        migrations.AddField(
            model_name='sugestaoturma',
            name='total_solicitacoes',
            field=models.IntegerField(null=True),
        ),
    ]
