# Generated by Django 3.0.5 on 2020-04-22 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20200414_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestaoturma',
            name='horarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Horario'),
        ),
    ]
