# Generated by Django 3.0.5 on 2020-04-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200421_2358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funcaogratificada',
            unique_together={('siape', 'id_unidade', 'inicio', 'atividade')},
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('sigla', 'bloco', 'centro', 'campus')},
        ),
    ]
