# Generated by Django 3.0.5 on 2020-04-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200422_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='campus',
            field=models.CharField(blank=True, choices=[('1', 'Campus Caicó'), ('2', 'Campus Currais Novos')], max_length=50, null=True),
        ),
    ]
