# Generated by Django 3.0.5 on 2020-04-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200423_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugestaoturma',
            old_name='horarios',
            new_name='horarios_set',
        ),
    ]
