# Generated by Django 3.0.5 on 2020-04-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20200425_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugestaoturma',
            old_name='horarios_set',
            new_name='horarios',
        ),
    ]
