# Generated by Django 3.0.5 on 2020-04-26 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200425_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestaoturma',
            name='criada_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sugestaoturma',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Curso'),
        ),
        migrations.AddField(
            model_name='sugestaoturma',
            name='semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sugestaoturma',
            name='tipo_vinculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
