# Generated by Django 3.0.5 on 2020-04-27 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0064_auto_20200426_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('solicitador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Discente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SugestaoTurma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('solicitador', 'turma')},
            },
        ),
        migrations.DeleteModel(
            name='SugestaoTurmaEstendida',
        ),
    ]
