# Generated by Django 3.0.5 on 2020-04-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20200427_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestaoturma',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
