# Generated by Django 3.0.6 on 2020-05-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_turma_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='campus',
            field=models.CharField(blank=True, choices=[('1', 'Campus Caicó'), ('2', 'Campus Currais Novos')], max_length=1, null=True),
        ),
    ]
