# Generated by Django 3.0.6 on 2020-05-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20200511_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaogratificada',
            name='observacoes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
