# Generated by Django 3.0.6 on 2020-05-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20200511_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='site',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='discente',
            name='sexo',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
