# Generated by Django 3.0.6 on 2020-05-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_docente_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Docente')),
                ('horarios', models.ManyToManyField(related_name='vinculos', to='core.Horario')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Turma')),
            ],
            options={
                'unique_together': {('docente', 'turma')},
            },
        ),
    ]
