# Generated by Django 3.0.6 on 2020-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_vinculodocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
