# Generated by Django 3.0.6 on 2020-05-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20200520_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurmaEstendida',
        ),
    ]
