# Generated by Django 3.0.6 on 2020-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_delete_turmaestendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='bloco',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sala',
            name='sigla',
            field=models.CharField(max_length=25),
        ),
    ]
