# Generated by Django 3.0.6 on 2020-06-04 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_enquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ComponenteCurricular')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Discente')),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='core.Enquete')),
                ('horarios', models.ManyToManyField(to='core.Horario')),
            ],
            options={
                'unique_together': {('componente', 'discente')},
            },
        ),
    ]
