# Generated by Django 3.0.6 on 2020-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20200604_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='tipo',
            field=models.CharField(choices=[('1', 'Completa'), ('2', 'Obrigatórias'), ('3', 'Optativas'), ('4', 'Parcial')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
