# Generated by Django 3.0.6 on 2020-06-07 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_enquete_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vototurma',
            name='tipo',
            field=models.CharField(choices=[('1', 'Válido'), ('2', 'Abstenção')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vototurma',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ComponenteCurricular'),
        ),
    ]
