# Generated by Django 3.0.6 on 2020-06-08 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20200606_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoDocenteSugestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField()),
                ('descricao_horario', models.CharField(max_length=150)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Docente')),
                ('horarios', models.ManyToManyField(related_name='vinculos_sugestao', to='core.Horario')),
                ('sugestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SugestaoTurma')),
            ],
            options={
                'unique_together': {('docente', 'sugestao')},
            },
        ),
    ]
