# Generated by Django 3.1.3 on 2020-11-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_enquete_qtd_discentes_ativos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.componentecurricular')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.discente')),
            ],
            options={
                'unique_together': {('discente', 'componente')},
            },
        ),
    ]
