# Generated by Django 3.1.3 on 2020-12-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='estruturacurricular',
            name='status',
            field=models.CharField(choices=[('1', 'Ativa'), ('2', 'Inativa')], max_length=1, null=True),
        ),
    ]
