# Generated by Django 3.1.3 on 2020-12-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_estruturacurricular_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_atividade_obrigatoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_complementar_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_ideal_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_maxima_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_minima_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='ch_nao_atividade_obrigatoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_ideal_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_maximo_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_minimo_semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_nao_atividade_obrigatorio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='cr_total_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='max_eletivos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='meses_conclusao_ideal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='meses_conclusao_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='meses_conclusao_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estruturacurricular',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
