# Generated by Django 3.1.7 on 2021-04-04 02:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20201130_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='semestre',
            field=models.CharField(max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.componentecurricular'),
            preserve_default=False,
        ),
    ]
