# Generated by Django 3.2.6 on 2021-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20210421_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.IntegerField()),
                ('id_discente', models.CharField(max_length=32)),
                ('id_curso', models.IntegerField()),
                ('unidade', models.IntegerField()),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reposicao', models.BooleanField()),
                ('faltas_unidade', models.IntegerField()),
                ('media_final', models.DecimalField(decimal_places=1, max_digits=3)),
                ('numero_total_faltas', models.IntegerField()),
                ('situacao', models.CharField(max_length=32)),
            ],
        ),
    ]
